config/routes.rb
Rails.application.routes.draw do

  namespace :intranet do
    get 'exame_resultados/new'
    get 'exame_resultados/edit'
  end

  constraints(subdomain: /^(?!mundo).+/) do
    
    resources :exame_tipos, except: [:show] do
      post 'edit_mode', on: :collection
      post 'leave_edit', on: :collection
    end
    resources :exame_requisicoes, except: [:destroy] do
      get 'novo_semelhante', on: :member
    end
    
    resources :familias, only: [:new, :edit] do
      post 'add_tutor', on: :member
      post 'add_paciente', on: :member
    end
    
    resources :pacientes, shallow: true do
      resources :atendimentos
    end

    resources :atendimentos, only: [:edit, :update] do      
    end

    patch 'update_apresentacao', controller: 'laboratorios'

    match '/', to: 'organizacoes#show', via: [:get]

    match '/iniciando_atendimento', to: 'atendimentos#iniciando', via: [:get], as: :iniciando_atendimento



    namespace :intranet do
      resources :exame_requisicoes, except: [:new, :create, :show, :destroy] do
        get 'receber', on: :member
        post 'anexar_resultado', on: :member
        post 'anexar_imagens', on: :member
        resources :exame_resultados, only: [:new, :create]
        get 'confirmar', on: :collection
        patch 'confirmar', on: :collection, action: :confirmar_recebimento
      end
      resources :exame_resultados, only: [:show, :edit, :update]

      match '/', to: 'laboratorios#show', via: [:get]
    end
  end

  resources :laboratorios, only: [:new, :create]


#  match '/', to: 'exame_requisicao#show', constraints: { subdomain: /.+/ }, via: [:get, :post, :put, :patch, :delete]

  match '/criar_clinica_demo', to: 'organizacoes#criar_clinica_demo', via: [:get]
  match '/conceder_permissoes_ao_labdemo', to: 'organizacoes#conceder_permissoes_ao_labdemo', via: [:get]
  
  devise_for :users
  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atendimento.rb
class Atendimento < ApplicationRecord
  belongs_to :paciente
end

app/models/clinica.rb
class Clinica < ApplicationRecord
  belongs_to :organizacao

  alias :org :organizacao

  def demo?
    org.subdomain.equals('clinica')
  end

end

app/models/endereco.rb
class Endereco < ApplicationRecord
end

app/models/exame_anexo.rb
class ExameAnexo < ApplicationRecord
  belongs_to :resultado, class_name: "ExameResultado"
  # Token para ofuscar url de download
  # https://github.com/thoughtbot/paperclip/wiki/Interpolations
  #
  has_secure_token :access_token
  
  has_attached_file :anexo, url: ":organizacao_id/:mes/resultados/:resultado_id/:class/:id/:access_token/:filename"

  validates_attachment_content_type :anexo, content_type: /.*pdf/

end

app/models/exame_imagem.rb
class ExameImagem < ApplicationRecord
  belongs_to :resultado, class_name: "ExameResultado"
  has_secure_token :access_token
  has_attached_file :imagem, url: ":organizacao_id/:mes/resultados/:resultado_id/:class/:id/:access_token/:filename"


  validates_attachment_content_type :imagem, content_type: /\Aimage\/.*\z/
end

app/models/exame_requisicao.rb
class ExameRequisicao < ApplicationRecord
  belongs_to :requisitante, class_name: "User"
  belongs_to :tipo, class_name: "ExameTipo"
  belongs_to :laboratorio
  has_one :resultado, class_name: "ExameResultado", foreign_key: "requisicao_id"


  include AASM

  aasm do
    state :aguardando_envio, :initial => true
    state :aguardando_resultado
    state :resultado_disponivel
    state :arquivado
    state :cancelado

    event :confirmar_recebimento do
      transitions :from => :aguardando_envio, :to => :aguardando_resultado
    end

    event :resultado_inserido do
      transitions :from => :aguardando_resultado, :to => :resultado_disponivel
    end

    event :arquivar do
      transitions :from => :resultado_disponivel, :to => :arquivado
    end

    event :cancelar do
      transitions :from => :aguardando_envio, :to => :cancelado
    end

  end

end

app/models/exame_resultado.rb
class ExameResultado < ApplicationRecord
  belongs_to :requisicao, class_name: "ExameRequisicao"
  belongs_to :tecnico, class_name: "User"
  has_many :anexos, class_name: "ExameAnexo", foreign_key: "resultado_id", inverse_of: 'resultado'
  has_many :imagens, class_name: "ExameImagem", foreign_key: "resultado_id", inverse_of: 'resultado'
end

app/models/exame_tipo.rb
class ExameTipo < ApplicationRecord
  belongs_to :laboratorio
  has_many :requisicoes, class_name: "ExameRequisicao", foreign_key: "tipo_id"
end

app/models/familia.rb
class Familia < ApplicationRecord
  belongs_to :clinica

  has_many :tutores
  has_many :pacientes
end

app/models/laboratorio.rb
class Laboratorio < ApplicationRecord
  has_many :exame_requisicoes
  has_many :exame_tipos, -> { order('nome asc')}
  has_many :unidades, -> { order('nome asc')}

  belongs_to :organizacao

  # Não consegui implementar essa validação
  # validates :subdomain, format: { with: /[a-z\-\_0-9]+/, message: "only allows letters" }
end

app/models/organizacao.rb
class Organizacao < ApplicationRecord
  resourcify
  belongs_to :dono, class_name: "User", optional: true
  has_one :laboratorio
  has_one :clinica

  scope :experimental, -> { where(experimental: true) }
  scope :nao_experimental, -> { where(experimental: false) }


  def Organizacao.criar_clinica_demo

    org = Organizacao.where(subdomain: 'clinica').take

    if org
      org.clinica.destroy if org.clinica
      
      # destroy organizacao
      org.destroy
    end
    
    dono = User.where('email': 'dono@mundo.vet').take ||  User.create('email': 'dono@mundo.vet', nome: 'Dono', password: 'mundovet')
    dono.password = 'mundovet'
    dono.save
    org = Organizacao.create(subdomain: 'clinica', dono: dono)
    clinica = Clinica.create(organizacao: org, nome: "Clínica Demonstrativa")

    org
  end
  
end

app/models/paciente.rb
class Paciente < ApplicationRecord
  belongs_to :familia
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/tutor.rb
class Tutor < ApplicationRecord
  belongs_to :familia
end

app/models/unidade.rb
class Unidade < ApplicationRecord
  belongs_to :laboratorio
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_gravatar
end

app/controllers/atendimentos_controller.rb
class AtendimentosController < OrganizacoesController

  layout "clinica"

  before_action :authenticate_user!

  before_action :set_paciente, only: [:new, :create]
  before_action :set_atendimento, only: [:edit, :update]

  def new
    @atendimento = Atendimento.new(paciente: @paciente)
  end

  def edit
  end

  def create
    #byebug
    @atendimento = Atendimento.create(paciente: @paciente)
    @atendimento.update(create_params)

    if @atendimento.save
      redirect_to edit_atendimento_path(@atendimento)
    else
      render :new
    end
  end


  def update
    # https://www.railstutorial.org/book/updating_and_deleting_users
    @atendimento.update(update_params)
    redirect_to edit_atendimento_path(@atendimento), notice: "Atendimento salvo."
  end

  private

  def set_paciente
    if params[:paciente_id]
      @paciente = Paciente.find(params[:paciente_id])
    else
      @paciente = Paciente.find(params[:atendimento][:paciente_id])
    end
  end

  def set_atendimento
    @atendimento = Atendimento.find(params[:id])
  end

  def atendimento_params
    params.permit(:id).permit(:anamnese).permit(atendimento: [:anamnese])
  end

  def update_params
    params.require(:atendimento).permit([:anamnese, :peso, :temperatura_retal, :batimentos_cardiaco, :frequencia_respiratoria, :observacoes, :achados_clinicos, :exames_complementares, :diagnostico_presuntivo, :terapia_do_presuntivo, :diagnostico_definitivo, :terapia_do_definitivo])
  end


  def create_params
    params.require(:atendimento).permit([:anamnese])
  end
end

app/helpers/atendimentos_helper.rb
module AtendimentosHelper
end

app/helpers/clinicas_helper.rb
module ClinicasHelper
end

app/helpers/familias_helper.rb
module FamiliasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tutores_helper.rb
module TutoresHelper
end

app/views/atendimentos/_form.html.erb
<% p = atendimento.paciente %>

<div id="cabecalho_atendimento" class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= p.nome %></h5>
          <div class="row">
            <div class='col'>
              Sexo: <%= p.sexo ? 'Masculino' : 'Feminino' %>
            </div>
            <div class='col'>
              Espécie: <%= p.especie %>
            </div>
            <div class='col'>
              Idade: 
                <% if p.data_nascimento %>
                  <%= time_ago_in_words p.data_nascimento %>
                <% else %>
                  Não informada
                <% end %>
            </div>
            <div class='col'>
              Raça: <%= p.raca %>
            </div>
          </div>
          <div class="row">
            <div class="col">
              Tutores: <%= (familia.tutores.map {|t| "#{t.nome}" + (t.telefones.blank?? "" : " (#{t.telefones})" )}).join(', ') %>
            </div>
          </div>    
        </div>
      </div>
    </div>
  </div>
</div>


<div class="container">
  <%= form_for [paciente, atendimento] do |f| %>
    <% paciente = atendimento.paciente %>

    <div class="form-group">
      <h2>Anamnese</h2>
      <%= f.text_area :anamnese, placeholder: 'Preenchar a anamnese', class: 'form-control', rows: "4" %>
    </div>

    <div class="form-group">
      <h2>Exame clínico</h2>
      <div class="row">
        <div class="col">
          <div class="input-group mb-3">
            <%= f.number_field :peso, class: 'form-control', placeholder:"Peso", step: :any, in: 0.0..200.0 %>
            <div class="input-group-append">
              <span class="input-group-text" id="basic-addon2">kg</span>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="input-group mb-3">
            <%= f.number_field :temperatura_retal, class: 'form-control', placeholder:"Temperatura retal", step: :any, in: 0.0..99.0 %>
            <div class="input-group-append">
              <span class="input-group-text" id="basic-addon2">°C</span>
            </div>
          </div>
        </div>


        <div class="col">
          <div class="input-group mb-3">
            <%= f.number_field :batimentos_cardiaco, class: 'form-control', placeholder:"Batimentos cardiaco", in: 0..100 %>
            <div class="input-group-append">
                <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
<span class="input-group-text" id="basic-addon2">/min</span>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="input-group mb-3">
            <%= f.number_field :frequencia_respiratoria, class: 'form-control', placeholder:"Frequência respiratória",  in: 0..200 %>
            <div class="input-group-append">
              <span class="input-group-text" id="basic-addon2">/min</span>
            </div>
          </div>
        </div>
        
      </div>


      <div class="form-group">
        <%= f.label :observacoes, "Observações" %>
        <%= f.text_area :observacoes, class: 'form-control', placeholder:"Observações", rows: 2 %>
      </div>

      <div class="form-group">
        <%= f.label :achados_clinicos, "Descrição dos achados clínicos" %>
        <%= f.text_area :achados_clinicos, class: 'form-control', placeholder:"Achados clínicos", rows: 3 %>
      </div>

    </div>

    <h2>Exames Complementares</h2>
    <div class="form-group">
      <%= f.text_area :exames_complementares, placeholder: 'Exames complementares', class: 'form-control', rows: "4" %>
    </div>
    
    <h2>Diagnósticos e terapias prescritas</h2>

    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">Diagnóstico presuntivo</span>
      </div>
      <%= f.text_field :diagnostico_presuntivo, class: 'form-control', placeholder:"Diagnóstico presuntivo"%>
    </div>

    <div class="form-group">
      <%= f.text_area :terapia_do_presuntivo, placeholder: 'Terapia prescrita devido ao diagnóstico presuntivo', class: 'form-control', rows: "4" %>
    </div>


    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">Diagnóstico definitivo</span>
      </div>
      <%= f.text_field :diagnostico_definitivo, class: 'form-control', placeholder:"Diagnóstico definitivo" %>
    </div>

    <div class="form-group">
      <%= f.text_area :terapia_do_definitivo, placeholder: 'Terapia prescrita devido ao diagnóstico definitivo', class: 'form-control', rows: "4" %>
    </div>


    <div class="actions form-group col-sm-2">
      <%= f.submit 'Salvar', class: "btn btn-primary", accesskey:"s" %>
    </div>


  <% end %>


</div>

app/views/atendimentos/edit.html.erb
<%= render 'form', atendimento: @atendimento, paciente: nil, familia: @atendimento.paciente.familia %>

app/views/atendimentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Atendimentos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @atendimentos.each do |atendimento| %>
      <tr>
        <td><%= link_to 'Show', atendimento %></td>
        <td><%= link_to 'Edit', edit_atendimento_path(atendimento) %></td>
        <td><%= link_to 'Destroy', atendimento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Atendimento', new_atendimento_path %>

app/views/atendimentos/iniciando.html.erb
<div class="container"

<h1>Atendimentos#iniciando</h1>
<p>Find me in app/views/atendimentos/iniciando.html.erb</p>


<% provide(:title, 'Cadastrando pacientes e tutores') %>
<% provide(:button_text, 'Salvar') %>

<%= render 'tutorform', tutor: Tutor.new %>

<div id="tutores_cadastrados">
</div>

</div>

app/views/atendimentos/new.html.erb
<%= render 'form', atendimento: @atendimento, paciente: @paciente, familia: @paciente.familia %>

app/views/atendimentos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_atendimento_path(@atendimento) %> |
<%= link_to 'Back', atendimentos_path %>