config/routes.rb
Rails.application.routes.draw do

  namespace :intranet do
    get 'exame_resultados/new'
    get 'exame_resultados/edit'
  end

  constraints(subdomain: /^(?!mundo).+/) do
    
    resources :exame_tipos, except: [:show] do
      post 'edit_mode', on: :collection
      post 'leave_edit', on: :collection
    end
    resources :exame_requisicoes, except: [:destroy] do
      get 'novo_semelhante', on: :member
    end
    
    resources :familias, only: [:new, :edit] do
      post 'add_tutor', on: :member
      post 'add_paciente', on: :member
    end
    
    resources :pacientes, shallow: true do
      resources :atendimentos
    end

    resources :atendimentos, only: [:edit, :update] do      
    end

    patch 'update_apresentacao', controller: 'laboratorios'

    match '/', to: 'organizacoes#show', via: [:get]

    match '/iniciando_atendimento', to: 'atendimentos#iniciando', via: [:get], as: :iniciando_atendimento



    namespace :intranet do
      resources :exame_requisicoes, except: [:new, :create, :show, :destroy] do
        get 'receber', on: :member
        post 'anexar_resultado', on: :member
        post 'anexar_imagens', on: :member
        resources :exame_resultados, only: [:new, :create]
        get 'confirmar', on: :collection
        patch 'confirmar', on: :collection, action: :confirmar_recebimento
      end
      resources :exame_resultados, only: [:show, :edit, :update]

      match '/', to: 'laboratorios#show', via: [:get]
    end
  end

  resources :laboratorios, only: [:new, :create]


#  match '/', to: 'exame_requisicao#show', constraints: { subdomain: /.+/ }, via: [:get, :post, :put, :patch, :delete]

  match '/criar_clinica_demo', to: 'organizacoes#criar_clinica_demo', via: [:get]
  match '/conceder_permissoes_ao_labdemo', to: 'organizacoes#conceder_permissoes_ao_labdemo', via: [:get]
  
  devise_for :users
  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atendimento.rb
class Atendimento < ApplicationRecord
  belongs_to :paciente
end

app/models/clinica.rb
class Clinica < ApplicationRecord
  belongs_to :organizacao

  alias :org :organizacao

  def demo?
    org.subdomain.equals('clinica')
  end

end

app/models/endereco.rb
class Endereco < ApplicationRecord
end

app/models/exame_anexo.rb
class ExameAnexo < ApplicationRecord
  belongs_to :resultado, class_name: "ExameResultado"
  # Token para ofuscar url de download
  # https://github.com/thoughtbot/paperclip/wiki/Interpolations
  #
  has_secure_token :access_token
  
  has_attached_file :anexo, url: ":organizacao_id/:mes/resultados/:resultado_id/:class/:id/:access_token/:filename"

  validates_attachment_content_type :anexo, content_type: /.*pdf/

end

app/models/exame_imagem.rb
class ExameImagem < ApplicationRecord
  belongs_to :resultado, class_name: "ExameResultado"
  has_secure_token :access_token
  has_attached_file :imagem, url: ":organizacao_id/:mes/resultados/:resultado_id/:class/:id/:access_token/:filename"


  validates_attachment_content_type :imagem, content_type: /\Aimage\/.*\z/
end

app/models/exame_requisicao.rb
class ExameRequisicao < ApplicationRecord
  belongs_to :requisitante, class_name: "User"
  belongs_to :tipo, class_name: "ExameTipo"
  belongs_to :laboratorio
  has_one :resultado, class_name: "ExameResultado", foreign_key: "requisicao_id"


  include AASM

  aasm do
    state :aguardando_envio, :initial => true
    state :aguardando_resultado
    state :resultado_disponivel
    state :arquivado
    state :cancelado

    event :confirmar_recebimento do
      transitions :from => :aguardando_envio, :to => :aguardando_resultado
    end

    event :resultado_inserido do
      transitions :from => :aguardando_resultado, :to => :resultado_disponivel
    end

    event :arquivar do
      transitions :from => :resultado_disponivel, :to => :arquivado
    end

    event :cancelar do
      transitions :from => :aguardando_envio, :to => :cancelado
    end

  end

end

app/models/exame_resultado.rb
class ExameResultado < ApplicationRecord
  belongs_to :requisicao, class_name: "ExameRequisicao"
  belongs_to :tecnico, class_name: "User"
  has_many :anexos, class_name: "ExameAnexo", foreign_key: "resultado_id", inverse_of: 'resultado'
  has_many :imagens, class_name: "ExameImagem", foreign_key: "resultado_id", inverse_of: 'resultado'
end

app/models/exame_tipo.rb
class ExameTipo < ApplicationRecord
  belongs_to :laboratorio
  has_many :requisicoes, class_name: "ExameRequisicao", foreign_key: "tipo_id"
end

app/models/familia.rb
class Familia < ApplicationRecord
  belongs_to :clinica

  has_many :tutores
  has_many :pacientes
end

app/models/laboratorio.rb
class Laboratorio < ApplicationRecord
  has_many :exame_requisicoes
  has_many :exame_tipos, -> { order('nome asc')}
  has_many :unidades, -> { order('nome asc')}

  belongs_to :organizacao

  # Não consegui implementar essa validação
  # validates :subdomain, format: { with: /[a-z\-\_0-9]+/, message: "only allows letters" }
end

app/models/organizacao.rb
class Organizacao < ApplicationRecord
  resourcify
  belongs_to :dono, class_name: "User", optional: true
  has_one :laboratorio
  has_one :clinica

  scope :experimental, -> { where(experimental: true) }
  scope :nao_experimental, -> { where(experimental: false) }


  def Organizacao.criar_clinica_demo

    org = Organizacao.where(subdomain: 'clinica').take

    if org
      org.clinica.destroy if org.clinica
      
      # destroy organizacao
      org.destroy
    end
    
    dono = User.where('email': 'dono@mundo.vet').take ||  User.create('email': 'dono@mundo.vet', nome: 'Dono', password: 'mundovet')
    dono.password = 'mundovet'
    dono.save
    org = Organizacao.create(subdomain: 'clinica', dono: dono)
    clinica = Clinica.create(organizacao: org, nome: "Clínica Demonstrativa")

    org
  end
  
end

app/models/paciente.rb
class Paciente < ApplicationRecord
  belongs_to :familia
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/tutor.rb
class Tutor < ApplicationRecord
  belongs_to :familia
end

app/models/unidade.rb
class Unidade < ApplicationRecord
  belongs_to :laboratorio
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_gravatar
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "mundovet"

  def index
    @experimentais = Organizacao.experimental
    @nao_experimentais = Organizacao.nao_experimental
  end
end

app/helpers/clinicas_helper.rb
module ClinicasHelper
end

app/helpers/familias_helper.rb
module FamiliasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tutores_helper.rb
module TutoresHelper
end

app/views/home/index.html.erb
<div class="container">
  <section class="jumbotron text-center" id="capa" style="background-image: url('https://s3-sa-east-1.amazonaws.com/mundovet-producao/mundo.vet/assets/capa2.jpg');">
      <h1 class="jumbotron-heading">Sistema para Laboratório Veterinário</h1>
<%#      <p class="lead text-muted">O sistema on-line que estamos construndo é ideal para quem estiver abrindo um laboratório veterinário ou possuir uma clínica veterinária.</p> %>
      <p>
        <a href="#funcionalidades" class="btn btn-primary my-2">Funcionalidades</a>
        <a href="#experimental" class="btn btn-info my-2">Experimentar</a>
        <a href="#demo" class="btn btn-info my-2">Laboratório demonstrativo</a>
<%#        <a href="#clinica" class="btn btn-info my-2">Clínica Veterinária</a>
        <a href="#autonomo" class="btn btn-info my-2">Veterinário autônomo</a>

        <%= link_to "Minha clínica", root_url(subdomain: 'clinica'), class: 'btn btn-primary my-2' % >
        <%= link_to "Criar clínica demonstrativa", criar_clinica_demo_path, class: 'btn btn-primary my-2', id: 'criar_clinica_demo' %>
      </p>
  </section>
</div>
<div class="container">

  <h2 id="laboratorio">Sistema para Laboratório Veterinário</h2>
  <div>
    <ul>
      <li>Você possui um laboratório veterinário?</li>
      <li>Envia os resultados dos exames para seus clientes por e-mail?</li>
      <li>Utiliza o facebook (ou uma página na web) para divulgar o seu negócio?</li>
    </ul>
    <p>Com o <strong>mundo.vet</strong> você terá um espaço na Web onde seus clientes poderão solicitar os exames e baixar os resultados.</p>
  </div>
  <h3 id="funcionalidades">Funcionalidades</h3>
  <p>Veja as funcionalidades do sistema:</p>
  <ul class="list-group mb-3">
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">Sistema completamente on-line</h6>
        <small class="text-muted">Não há necessidade de instalação ou backups, acesse através do seu navegador, celular ou tablet.</small>
      </div>
    </li>
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">Não há necessidade de adquirir um domínio.</h6>
        <small class="text-muted"> O seu laboratório ganha um subdomínio dentro do mundo.vet, exemplo: <strong>seulab.mundo.vet</strong></small>
      </div>
    </li>
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">Pode ser utilizado com um domínio próprio</h6>
        <small class="text-muted">Já possui um domínio? Não tem problema, você pode utilizá-lo, nós te ajudamos na configuração. Exemplo: <strong>cliente.seudominio.com.br</strong></small>
      </div>
    </li>
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">Anexe PDFs como resultados</h6>
        <small class="text-muted">Os resultados dos exames serão arquivos PDFs criados por você e anexados ao sistema. Não há telas específicas, você tem liberdade para gerar qualquer PDF com o resultado.</small>
      </div>
    </li>
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">Seus clientes solicitam os exames on-line</h6>
        <small class="text-muted">Através do sistema on-line seus clientes (veterinários) cadastram solicitações de exames, acompanham os status dos exames e acessam os resultados.</small>
      </div>
    </li>
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">Diferentes perfis de acesso</h6>
        <small class="text-muted">Usuários com diferentes permissões de acesso: secretário, técnico e dono.</small>
      </div>
    </li>

<%#    
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">Seu cliente terá acesso ao nosso sistema de clínica veterinária</h6>
        <small class="text-muted">Seu cliente ganha acesso ao sistema de clínica veterinária on-line do <strong>mundo.vet</strong>, onde poderá acessar os históricos de exames dos animais ou gerenciar a clínica que possuir.</small>
      </div>
    </li>
%>    
  </ul>
  <h3>Problemas com soluções personalizadas</h3>
  <p>Muitos laboratórios, antes do <strong>mundo.vet</strong>, optavam por contratar soluções personalizadas, mas elas tem os seguintes problemas:</p>
    <%# <p>Nós estamos oferecendo a você simplicidade e baixo custo, veja as funcionalidades do sistema para laboratório:</p> %>
    <ul>
      <li>A construção é cara: contratar uma empresa ou desenvolvedor para criar uma solução personalizada é extremamente onerosa.</li>
      <li>Manter uma infraestrtura também é caro: os sistemas personalizados requerem pagar um servidor dedicado exclusivo, não havendo como diluir os custos.</li>
      <li>O suporte é caro ou inexistente: alguns anos após a criação do sistema, quem o desenvolveu pode está indisponível para fornecer o suporte. </li>
      <li>Implementar novas funcionalidades exige um grande custo.</li>
      <li>Problemas de segurança: a maioria dos sistemas personalizados não são atualizados constantemente por isso ficam a mercer de invasões.</li>
    </ul>

  <h3 id="experimental">Experimentar o sistema de laboratório do mundo.vet</h3>
  <p>Ao clicar no botão abaixo, nós criamos um laboratório exclusivo para você experimentar o sistema, esta é a <strong>melhor alternativa para você conhecer o nosso sistema</strong>.</p>

    <div class="text-center mb-3">
      <%= link_to "Criar um laboratório para experimentar", new_laboratorio_path, class: 'btn  btn-info my-2' %>
    </div>

  <h3 id="demo">Laboratório Demonstrativo</h3>
    <p>Diferente do laboratório experimental, o laboratório demonstrativo já encontra-se criado, sendo uma outra alternativa para conhecer como o sistema funciona:<p>
    <div class="text-center mb-2">
      <%= link_to "Acessar o Laboratório demonstrativo como cliente", root_url(subdomain: 'labdemo'), class: 'btn  btn-info my-2' %>
    </div>
    <p>Os funcionários do laboratório trabalham na <strong>Intranet</strong> e necessitam de permissões específicas para acesso. O botão a seguir lhe concederá permissões para acessar <strong>Intranet</strong> e anexar resultados das solicitações de exames. </p>
    <ul>
      <li>Qualquer usuário poderá solicitar permissões de acesso a Intranet, portanto considere este um ambiente compartilhado entre todos os usuários que desejarem experimentar o sistema.</li>
      <li>Fique a vontade para realizar quaisquer ações no laboratório demonstrativo.</li>
      <li>Caso você ainda não tenha um cadastro será solicitado que realize-o.</li>      
    </ul>

    <div class="text-center">
      <%= link_to "Conceder permissões e acessar Intranet do laboratório demonstrativo", conceder_permissoes_ao_labdemo_path, class: 'btn  btn-info my-2' %>
    </div>

  
  <h2 id="preco">Preço</h2>
  <div class="card-deck mb-3 text-center">
    <div class="card mb-4 box-shadow">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Laboratório veterinário</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">R$ 40 <small class="text-muted">/ mês</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>Página personalizada</li>
          <li>Domínio fácil ou customizado</li>
          <li>Acesso ao sistema web</li>
          <li>Segurança</li>
          <li>Suporte</li>
        </ul>
          <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
            Contratar
          </a>
        <div class="collapse" id="collapseExample">
          <div class="card card-body">
            Por enquanto as solicitações de criação de laboratórios devem ser realizadas por e-mail <strong>contato@mundo.vet</strong> ou por telefone/Whatsapp: <strong>(83) 98108-1977</strong>.
          </div>
        </div>        
      </div>
    </div>
  </div>

  <h2>Laboratórios experimentais</h2>
  <p>Veja alguns laboratórios experimentais que foram criados: </p>
  <ul class="list-group mb-3">
    <% @experimentais.each do |org| %>
      <% next unless org.laboratorio %>    
      <% lab = org.laboratorio %>
      <li class="list-group-item">
        <%= link_to root_url(subdomain: org.subdomain) do %>
          <%= lab.nome %> - <%= root_url(subdomain: org.subdomain) %>
        <% end %>
      </li>
    <% end %>
  </ul>


  <h2>Laboratórios clientes</h2>
  <p>Veja alguns laboratórios que utilizam os nossos serviços: </p>
  <ul class="list-group mb-3">
    <% @nao_experimentais.each do |org| %>
      <% next unless org.laboratorio %>
      <% lab = org.laboratorio %>
      <li class="list-group-item">
        <%= link_to root_url(subdomain: lab.organizacao.subdomain) do %>
          <%= image_tag lab.organizacao.dono.gravatar_url(:size => 64) %> 
          <%= lab.nome %>
        <% end %>
      </li>
    <% end %>
  </ul>

<%#
  <h2 id="clinica">Clínica veterinária</h2>
  <div>
    <p>Estamos construindo um sistema para clínica veterinária, será disponível em breve.<p>
    <%# <p>Nós estamos oferecendo a você simplicidade e baixo custo, veja as funcionalidades do sistema para laboratório:</p>
  </div>

  <h2 id="autonomo">Veterinário autônomo</h2>
  <div>
    <p>O sistema de clínica veterinária, em construção, poderá ser utilizado por veterinários autônomos que trabalham em vários locais e desejam manter registros sobre seus clientes e pacientes.<p>
    <%# <p>Nós estamos oferecendo a você simplicidade e baixo custo, veja as funcionalidades do sistema para laboratório:</p> 
  </div>
%>
  <h2 id="quem-somos">Quem somos</h2>
  <div>
    <p>Nós somos uma <em>startup</em> de desenvolvimento de software para veterinários. Nós acreditamos que podemos construir soluções simples e de baixo custo.</p>
    <p>Iniciamos nossas atividades produzindo um <strong>sistema para laboratórios veterinários</strong> e em breve lançaremos outro sistema para veterinários gerenciarem os atendimentos de pacientes e tutores.</p>
  </div>


  <h2 id="contato">Contato</h2>
  <p>
    Para contratar o sistema para sua clínica ou laboratório entre em contato por telefone: <strong>(83) 98108-1977</strong> ou por email: <strong>contato@mundo.vet</strong>.
  </p> 

</div>