config/routes.rb
Rails.application.routes.draw do

  namespace :intranet do
    get 'exame_resultados/new'
    get 'exame_resultados/edit'
  end

  constraints(subdomain: /^(?!mundo).+/) do
    
    resources :exame_tipos, except: [:show] do
      post 'edit_mode', on: :collection
      post 'leave_edit', on: :collection
    end
    resources :exame_requisicoes, except: [:destroy] do
      get 'novo_semelhante', on: :member
    end
    
    resources :familias, only: [:new, :edit] do
      post 'add_tutor', on: :member
      post 'add_paciente', on: :member
    end
    
    resources :pacientes, shallow: true do
      resources :atendimentos
    end

    resources :atendimentos, only: [:edit, :update] do      
    end

    patch 'update_apresentacao', controller: 'laboratorios'

    match '/', to: 'organizacoes#show', via: [:get]

    match '/iniciando_atendimento', to: 'atendimentos#iniciando', via: [:get], as: :iniciando_atendimento



    namespace :intranet do
      resources :exame_requisicoes, except: [:new, :create, :show, :destroy] do
        get 'receber', on: :member
        post 'anexar_resultado', on: :member
        post 'anexar_imagens', on: :member
        resources :exame_resultados, only: [:new, :create]
        get 'confirmar', on: :collection
        patch 'confirmar', on: :collection, action: :confirmar_recebimento
      end
      resources :exame_resultados, only: [:show, :edit, :update]

      match '/', to: 'laboratorios#show', via: [:get]
    end
  end

  resources :laboratorios, only: [:new, :create]


#  match '/', to: 'exame_requisicao#show', constraints: { subdomain: /.+/ }, via: [:get, :post, :put, :patch, :delete]

  match '/criar_clinica_demo', to: 'organizacoes#criar_clinica_demo', via: [:get]
  match '/conceder_permissoes_ao_labdemo', to: 'organizacoes#conceder_permissoes_ao_labdemo', via: [:get]
  
  devise_for :users
  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/exame_requisicoes_controller.rb
class ExameRequisicoesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_exame_requisicao, only: [:show, :edit, :update, :destroy, :novo_semelhante]


  def show
    authorize @exame_requisicao
  end

  def edit
    authorize @exame_requisicao
  end

  def new
    if current_user.nome.blank? || current_user.cpf.blank? || current_user.crmv.blank? || current_user.endereco.blank? || current_user.telefone.blank?
      redirect_to edit_user_registration_path, alert: "Atualize o perfil completo para poder solicitar exames."
    elsif @lab.exame_tipos.empty?
      redirect_to root_url(subdomain: @lab.organizacao.subdomain), alert: "Enquanto não houver tipos de exames cadastrados nesse laboratório não será possível solicitar novos exames."
    else
      @exame_requisicao = ExameRequisicao.new
    end
  end

  def novo_semelhante
    if current_user.nome.blank? || current_user.cpf.blank? || current_user.crmv.blank? || current_user.endereco.blank? || current_user.telefone.blank?
      redirect_to edit_user_registration_path, alert: "Atualize o perfil completo para poder solicitar exames."
    else
      @exame_requisicao = @exame_requisicao.dup
      render :new
    end
  end

  def index
    @exame_requisicoes = ExameRequisicao.where(requisitante: current_user, laboratorio: @lab).order(:id).reverse_order

    # não é necessário authorize, qualquer um pode consultar os seus exames
    #authorize @lab, :listar_requisicoes?
  end

  def create
    @exame_requisicao = ExameRequisicao.new(exame_requisicao_params)
    @exame_requisicao.laboratorio = @lab
    @exame_requisicao.requisitante = current_user
    @exame_requisicao.tipo = ExameTipo.find(params[:exame_requisicao][:tipo_id])

    authorize @exame_requisicao

    if @exame_requisicao.save
      redirect_to @exame_requisicao, notice: 'Requisiçao de Exame criada com sucesso.'
    else
      render :new
    end
  end

  # PATCH/PUT /exame_requisicoes/1
  def update
    if @exame_requisicao.update(exame_requisicao_params)
      authorize @exame_requisicao
      redirect_to @exame_requisicao, notice: 'Requisiçao de Exame atualizada com sucesso.'
    else
      render :edit
    end

  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_exame_requisicao
    @exame_requisicao = ExameRequisicao.find(params[:id])
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def exame_requisicao_params
    params.require(:exame_requisicao).permit(:proprietario, :nome, :idade, :especie, :raca, :observacoes, :tipo_id, :suspeita_clinica )
  end

end

app/controllers/intranet/exame_requisicoes_controller.rb
module Intranet

  class ExameRequisicoesController < IntranetController

    before_action :authenticate_user!
    before_action :set_exame_requisicao, only: [:show, :edit, :update, :destroy, :receber, :anexar_resultado, :anexar_imagens, :confirmar_recebimento]

    def edit
      authorize [:intranet, @exame_requisicao]
    end

    def anexar_resultado
      authorize [:intranet, @exame_requisicao], :enviar_resultado?

      @exame_requisicao.resultado ||= ExameResultado.create(requisicao: @exame_requisicao, tecnico: current_user)

      #byebug

      #params[:exame_anexo][:anexo].each do |anexo|
      #  @exame_requisicao.resultado.anexos.create(anexo)
      #end
      #params[:images].each { |image|  @gallery.pictures.create(image: image) }

      anexo = @exame_requisicao.resultado.anexos.create(anexo_params)

      @exame_requisicao.resultado_inserido! unless  @exame_requisicao.resultado_disponivel?

      redirect_to edit_intranet_exame_requisicao_path(@exame_requisicao), notice: 'Anexo adicionado.'
    end


    def anexar_imagens
      authorize [:intranet, @exame_requisicao], :enviar_resultado?

      @exame_requisicao.resultado ||= ExameResultado.create(requisicao: @exame_requisicao, tecnico: current_user)
      
      imagem_params.each do |imagem|
        img = @exame_requisicao.resultado.imagens.create(imagem: imagem)
      end

      redirect_to edit_intranet_exame_requisicao_path(@exame_requisicao), notice: 'Imagens adicionadas.'
    end

    def receber
      authorize [:intranet, @exame_requisicao], :confirmar_recebimento?

      @exame_requisicao.confirmar_recebimento!
      redirect_to intranet_exame_requisicoes_path, notice: "O recebimento foi confirmado."
    end
    
    def index
      @exame_requisicoes = ExameRequisicao.where(laboratorio: @lab).order(:id).reverse_order
      authorize [:intranet, @lab], :index_requisicoes?
    end

    def confirmar
      authorize [:intranet, @lab], :index_requisicoes?
      @exame_requisicoes = ExameRequisicao.where(laboratorio: @lab, aasm_state: 'aguardando_envio' ).order(:id)
    end

    def confirmar_recebimento
      authorize [:intranet, @exame_requisicao], :confirmar_recebimento?
      @exame_requisicao.confirmar_recebimento!
      #redirect_to confirmar_intranet_exame_requisicoes_path
    end

    # PATCH/PUT /exame_requisicoes/1
    def update
      authorize [:intranet, @exame_requisicao]
      if @exame_requisicao.update(exame_requisicao_params)
        redirect_to @exame_requisicao, notice: 'Exame requisicao was successfully updated.'
      else
        render :edit
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_exame_requisicao
      @exame_requisicao = ExameRequisicao.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def exame_requisicao_params
      params.require(:exame_requisicao).permit(:proprietario, :nome, :idade, :especie, :raca, :observacoes)
    end

    def anexo_params
      #params.require(:anexo)
      params.require(:exame_anexo).permit(:anexo)
    end
    def imagem_params
      #params.require(:anexo)
      params.require(:imagens)

    end

  end

end

app/controllers/intranet/exame_resultados_controller.rb
class Intranet::ExameResultadosController < ApplicationController
  def new
  end

  def edit
  end

  def _form
  end
end

app/controllers/intranet/laboratorios_controller.rb
module Intranet
  class LaboratoriosController < IntranetController
    def show
      authorize @lab
    end
  end
end

app/controllers/intranet_controller.rb
class IntranetController < ApplicationController

  before_action :authenticate_user!
  before_action :verifica_permissao_global

  def pundit_user
    def current_user.at_intranet?
      true
    end
    def current_user.at_lab
      @lab
    end
    current_user
  end

  private 
  
  def verifica_permissao_global
  end

end

app/helpers/exame_requisicoes_helper.rb
module ExameRequisicoesHelper
end

app/helpers/intranet/exame_resultados_helper.rb
module Intranet::ExameResultadosHelper
end

app/views/intranet/exame_requisicoes/_form.html.erb
<%= form_with(model: exame_requisicao, local: true) do |f| %>
  <% if exame_requisicao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exame_requisicao.errors.count, "error") %> prohibited this exame_requisicao from being saved:</h2>

      <ul>
      <% exame_requisicao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo, "Tipo do exame" %>
    <%= f.collection_select(:tipo_id, @lab.exame_tipos, :id, :nome) %>
  </div>


  <div class="field">
    <%= f.label :proprietario, "Nome do proprietário" %>
    <%= f.text_field :proprietario, id: :exame_requisicao_proprietario %>
  </div>

  <div class="field">
    <%= f.label :nome, "Nome do animal" %>
    <%= f.text_field :nome, id: :exame_requisicao_nome %>
  </div>

  <div class="field">
    <%= f.label :idade %>
    <%= f.text_field :idade, id: :exame_requisicao_idade %>
  </div>

  <div class="field">
    <%= f.label :especie, "Espécie" %>
    <%= f.text_field :especie, id: :exame_requisicao_especie %>
  </div>

  <div class="field">
    <%= f.label :raca, "Raça" %>
    <%= f.text_field :raca, id: :exame_requisicao_raca %>
  </div>

  <div class="field">
    <%= f.label :observacoes, "Observações" %>
    <%= f.text_area :observacoes, id: :exame_requisicao_observacoes %>
  </div>

  <div class="actions">
    <%= f.submit yield(:button_text) %>
  </div>
<% end %>

app/views/intranet/exame_requisicoes/confirmar.html.erb
<%= link_to 'Voltar', intranet_path %>



<h1>Requisições de exames à confirmar</h1>

<div id="quadro"></div>

<%= form_with url: confirmar_intranet_exame_requisicoes_path, method: :patch do |f| %>

<table class="table text-center">
  <thead class="thead-dark">
    <tr>
      <th>Data</th>
      <th>Protocolo</th>
      <th>Tipo</th>      
      <th>Requisitante</th>
      <th>Proprietário</th>
      <th>Nome do animal</th>
      <th>Status</th>
      <th colspan="2">Ação</th>
    </tr>
  </thead>

  <tbody>
    <% @exame_requisicoes.each do |exame_requisicao| %>
      <tr id="exame_requisicao<%=exame_requisicao.id%>" class="<%= exame_requisicao.aguardando_envio?? 'table-warning' : exame_requisicao.aguardando_resultado?? 'table-info' : ''%>">
        <td><%= exame_requisicao.created_at.strftime("%d/%m/%Y") %></td>
        <td><%= link_to exame_requisicao.id, edit_intranet_exame_requisicao_path(exame_requisicao) %></td>
        <td><%= exame_requisicao.tipo.nome %></td>
        <td><%= link_to (exame_requisicao.requisitante.nome or exame_requisicao.requisitante.email), edit_intranet_exame_requisicao_path(exame_requisicao)%></td>
        <td><%= link_to exame_requisicao.proprietario, edit_intranet_exame_requisicao_path(exame_requisicao) %></td>
        <td><%= link_to exame_requisicao.nome, edit_intranet_exame_requisicao_path(exame_requisicao) %></td>
        <td id="status<%=exame_requisicao.id%>"><%= t (exame_requisicao.aasm_state) %></td>
        <td id="acoes<%=exame_requisicao.id%>">

          <%#= button_to 'Confirmar recebimento', confirmar_intranet_exame_requisicao_path(exame_requisicao.id), id: "confirmar_#{exame_requisicao.id}", class: 'btn btn-outline-primary' if exame_requisicao.may_confirmar_recebimento?, value: exame_requisicao.id%>
          <%= f.button 'Confirmar recebimento', value: exame_requisicao.id, id: "confirmar_#{exame_requisicao.id}", name: "id", class: 'btn btn-primary' %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

app/views/intranet/exame_requisicoes/confirmar_recebimento.js.erb
$( "#status<%=@exame_requisicao.id%>" ).replaceWith("<td id=\"status<%=@exame_requisicao.id%>\"><%=t @exame_requisicao.aasm_state%></td>");
$( "#acoes<%=@exame_requisicao.id%>"  ).replaceWith("<td id=\"acoes<%=@exame_requisicao.id%>\"></td>");

app/views/intranet/exame_requisicoes/edit.html.erb
<div class="container">

<% unless @exame_requisicao.aguardando_envio? %>
<h1 id="resultado">Resultado</h1>
<div id="menu">
<!--
  <%= form_tag({action: :anexar_resultado}, multipart: true) do %>
    <%= file_field_tag 'anexo' %>
    <%= submit_tag 'Anexar ao resultado', class: 'btn btn-default' %>
  <% end %>
-->

  <div class="form-group">
    <%= form_for ExameAnexo.new, url: anexar_resultado_intranet_exame_requisicao_path(@exame_requisicao), html: { multipart: true } do |f| %>
      <%= f.file_field :anexo %>
      <%= f.submit 'Anexar ao resultado', class: 'btn btn-default' %>
      <small class="form-text text-muted">Permite anexar um PDF por vez. Não é permitido excluir o arquivo após submissão.</small>
    <% end %>
  </div>

</div>

<% if @exame_requisicao.resultado %>
  <div id="anexos">
    <ul>
      <% @exame_requisicao.resultado.anexos.each_with_index do |anexo,index| %>
        <li><%= link_to "Resultado-#{index+1}-#{l anexo.created_at}", anexo.anexo.url, id: "resultado-anexo#{index+1}"%></li>
      <% end %>
      <% @exame_requisicao.resultado.imagens.each_with_index do |imagem,index| %>
        <li><%= link_to "Imagem-#{index+1}", imagem.imagem.url, id: "resultado-imagem#{index+1}"%></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= form_for ExameImagem.new, url: anexar_imagens_intranet_exame_requisicao_path(@exame_requisicao), html: { multipart: true } do |f| %>
    <%= file_field_tag "imagens[]", type: :file, multiple: true %>
    <%= f.submit 'Anexar imagens', class: 'btn btn-default' %>
    <small class="form-text text-muted">Permite anexar múltiplas imagens por vez. Não é permitido excluir o arquivo após submissão.</small>
  <% end %>
</div>
<% end %>


<h1>Requisição de exame</h1>

<%= link_to 'Confirmar recebimento', receber_intranet_exame_requisicao_path(@exame_requisicao), id: "confirmar_recebimento", class: 'btn btn-outline-primary' if @exame_requisicao.may_confirmar_recebimento?%>

<p>
  <strong>Protocolo:</strong>
  <%= @exame_requisicao.id %>
</p>

<p>
  <strong>Requisitante:</strong>
  <%= @exame_requisicao.requisitante.nome %>

  <strong>CRMV:</strong>
  <%= @exame_requisicao.requisitante.crmv %>

  <strong>Telefone:</strong>
  <%= @exame_requisicao.requisitante.telefone %>
</p>


<p>
  <strong>Proprietario:</strong>
  <%= @exame_requisicao.proprietario %>

  <strong>Nome do animal:</strong>
  <%= @exame_requisicao.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @exame_requisicao.idade %>
  <strong>Especie:</strong>
  <%= @exame_requisicao.especie %>
  <strong>Raca:</strong>
  <%= @exame_requisicao.raca %>
</p>

<p>
  <strong>Suspeita clínica:</strong>
  <%= @exame_requisicao.suspeita_clinica %>
</p>


<p>
  <strong>Observações:</strong>
  <%= @exame_requisicao.observacoes %>
</p>

<p>
  <strong>Status:</strong>
  <%= t @exame_requisicao.aasm_state %>
</p>

<%= link_to 'Voltar', intranet_exame_requisicoes_path %>

</div>

app/views/intranet/exame_requisicoes/index.html.erb
<%= link_to 'Voltar', intranet_path %>


<h1>Requisições de exames</h1>

<table class="table text-center">
  <thead class="thead-dark">
    <tr>
      <th>Data</th>
      <th>Protocolo</th>
      <th>Tipo</th>      
      <th>Requisitante</th>
      <th>Proprietário</th>
      <th>Nome do animal</th>
      <th>Status</th>
      <th colspan="2">Ação</th>
    </tr>
  </thead>

  <tbody>
    <% @exame_requisicoes.each do |exame_requisicao| %>
      <tr id="exame_requisicao<%=exame_requisicao.id%>" class="<%= exame_requisicao.aguardando_envio?? 'table-warning' : exame_requisicao.aguardando_resultado?? 'table-info' : ''%>">
        <td><%= exame_requisicao.created_at.strftime("%d/%m/%Y") %></td>
        <td><%= link_to exame_requisicao.id, edit_intranet_exame_requisicao_path(exame_requisicao) %></td>
        <td><%= exame_requisicao.tipo.nome %></td>
        <td><%= link_to (exame_requisicao.requisitante.nome or exame_requisicao.requisitante.email), edit_intranet_exame_requisicao_path(exame_requisicao)%></td>
        <td><%= link_to exame_requisicao.proprietario, edit_intranet_exame_requisicao_path(exame_requisicao) %></td>
        <td><%= link_to exame_requisicao.nome, edit_intranet_exame_requisicao_path(exame_requisicao) %></td>
        <td><%= t (exame_requisicao.aasm_state) %></td>
        <td>
          <%= link_to 'Confirmar recebimento', receber_intranet_exame_requisicao_path(exame_requisicao), id: "confirmar_recebimento", class: 'btn btn-outline-primary' if exame_requisicao.may_confirmar_recebimento?%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/intranet/exame_requisicoes/show.html.erb
<div id="menu">
  <ul>
    <li><%= link_to 'Inserir resultado', edit_exame_requisicao_path(@exame_requisicao)%></li>
  </ul>
</div>

<h1>Requisição de exame</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Proprietario:</strong>
  <%= @exame_requisicao.proprietario %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @exame_requisicao.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @exame_requisicao.idade %>
</p>

<p>
  <strong>Especie:</strong>
  <%= @exame_requisicao.especie %>
</p>

<p>
  <strong>Raca:</strong>
  <%= @exame_requisicao.raca %>
</p>

<p>
  <strong>Observacoes:</strong>
  <%= @exame_requisicao.observacoes %>
</p>

<p>
  <strong>Status:</strong>
  Aguardando envio da coleta
</p>

<h2 class="instrucoes">Instruções para entrega da coleta</h2>


<ul>
  <li>Escreva no recipiente da coleta o número do protocolo e o nome do animal: <strong>#<%=@exame_requisicao.id%> - <%=@exame_requisicao.nome%></strong></li>
</ul>


<%= link_to 'Editar', edit_exame_requisicao_path(@exame_requisicao) %> |
<%= link_to 'Voltar', exame_requisicoes_path %>