config/routes.rb
Rails.application.routes.draw do

  namespace :intranet do
    get 'exame_resultados/new'
    get 'exame_resultados/edit'
  end

  constraints(subdomain: /^(?!mundo).+/) do
    
    resources :exame_tipos, except: [:show] do
      post 'edit_mode', on: :collection
      post 'leave_edit', on: :collection
    end
    resources :exame_requisicoes, except: [:destroy] do
      get 'novo_semelhante', on: :member
    end
    
    resources :familias, only: [:new, :edit] do
      post 'add_tutor', on: :member
      post 'add_paciente', on: :member
    end
    
    resources :pacientes, shallow: true do
      resources :atendimentos
    end

    resources :atendimentos, only: [:edit, :update] do      
    end

    patch 'update_apresentacao', controller: 'laboratorios'

    match '/', to: 'organizacoes#show', via: [:get]

    match '/iniciando_atendimento', to: 'atendimentos#iniciando', via: [:get], as: :iniciando_atendimento



    namespace :intranet do
      resources :exame_requisicoes, except: [:new, :create, :show, :destroy] do
        get 'receber', on: :member
        post 'anexar_resultado', on: :member
        post 'anexar_imagens', on: :member
        resources :exame_resultados, only: [:new, :create]
        get 'confirmar', on: :collection
        patch 'confirmar', on: :collection, action: :confirmar_recebimento
      end
      resources :exame_resultados, only: [:show, :edit, :update]

      match '/', to: 'laboratorios#show', via: [:get]
    end
  end

  resources :laboratorios, only: [:new, :create]


#  match '/', to: 'exame_requisicao#show', constraints: { subdomain: /.+/ }, via: [:get, :post, :put, :patch, :delete]

  match '/criar_clinica_demo', to: 'organizacoes#criar_clinica_demo', via: [:get]
  match '/conceder_permissoes_ao_labdemo', to: 'organizacoes#conceder_permissoes_ao_labdemo', via: [:get]
  
  devise_for :users
  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atendimento.rb
class Atendimento < ApplicationRecord
  belongs_to :paciente
end

app/models/clinica.rb
class Clinica < ApplicationRecord
  belongs_to :organizacao

  alias :org :organizacao

  def demo?
    org.subdomain.equals('clinica')
  end

end

app/models/endereco.rb
class Endereco < ApplicationRecord
end

app/models/exame_anexo.rb
class ExameAnexo < ApplicationRecord
  belongs_to :resultado, class_name: "ExameResultado"
  # Token para ofuscar url de download
  # https://github.com/thoughtbot/paperclip/wiki/Interpolations
  #
  has_secure_token :access_token
  
  has_attached_file :anexo, url: ":organizacao_id/:mes/resultados/:resultado_id/:class/:id/:access_token/:filename"

  validates_attachment_content_type :anexo, content_type: /.*pdf/

end

app/models/exame_imagem.rb
class ExameImagem < ApplicationRecord
  belongs_to :resultado, class_name: "ExameResultado"
  has_secure_token :access_token
  has_attached_file :imagem, url: ":organizacao_id/:mes/resultados/:resultado_id/:class/:id/:access_token/:filename"


  validates_attachment_content_type :imagem, content_type: /\Aimage\/.*\z/
end

app/models/exame_requisicao.rb
class ExameRequisicao < ApplicationRecord
  belongs_to :requisitante, class_name: "User"
  belongs_to :tipo, class_name: "ExameTipo"
  belongs_to :laboratorio
  has_one :resultado, class_name: "ExameResultado", foreign_key: "requisicao_id"


  include AASM

  aasm do
    state :aguardando_envio, :initial => true
    state :aguardando_resultado
    state :resultado_disponivel
    state :arquivado
    state :cancelado

    event :confirmar_recebimento do
      transitions :from => :aguardando_envio, :to => :aguardando_resultado
    end

    event :resultado_inserido do
      transitions :from => :aguardando_resultado, :to => :resultado_disponivel
    end

    event :arquivar do
      transitions :from => :resultado_disponivel, :to => :arquivado
    end

    event :cancelar do
      transitions :from => :aguardando_envio, :to => :cancelado
    end

  end

end

app/models/exame_resultado.rb
class ExameResultado < ApplicationRecord
  belongs_to :requisicao, class_name: "ExameRequisicao"
  belongs_to :tecnico, class_name: "User"
  has_many :anexos, class_name: "ExameAnexo", foreign_key: "resultado_id", inverse_of: 'resultado'
  has_many :imagens, class_name: "ExameImagem", foreign_key: "resultado_id", inverse_of: 'resultado'
end

app/models/exame_tipo.rb
class ExameTipo < ApplicationRecord
  belongs_to :laboratorio
  has_many :requisicoes, class_name: "ExameRequisicao", foreign_key: "tipo_id"
end

app/models/familia.rb
class Familia < ApplicationRecord
  belongs_to :clinica

  has_many :tutores
  has_many :pacientes
end

app/models/laboratorio.rb
class Laboratorio < ApplicationRecord
  has_many :exame_requisicoes
  has_many :exame_tipos, -> { order('nome asc')}
  has_many :unidades, -> { order('nome asc')}

  belongs_to :organizacao

  # Não consegui implementar essa validação
  # validates :subdomain, format: { with: /[a-z\-\_0-9]+/, message: "only allows letters" }
end

app/models/organizacao.rb
class Organizacao < ApplicationRecord
  resourcify
  belongs_to :dono, class_name: "User", optional: true
  has_one :laboratorio
  has_one :clinica

  scope :experimental, -> { where(experimental: true) }
  scope :nao_experimental, -> { where(experimental: false) }


  def Organizacao.criar_clinica_demo

    org = Organizacao.where(subdomain: 'clinica').take

    if org
      org.clinica.destroy if org.clinica
      
      # destroy organizacao
      org.destroy
    end
    
    dono = User.where('email': 'dono@mundo.vet').take ||  User.create('email': 'dono@mundo.vet', nome: 'Dono', password: 'mundovet')
    dono.password = 'mundovet'
    dono.save
    org = Organizacao.create(subdomain: 'clinica', dono: dono)
    clinica = Clinica.create(organizacao: org, nome: "Clínica Demonstrativa")

    org
  end
  
end

app/models/paciente.rb
class Paciente < ApplicationRecord
  belongs_to :familia
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/tutor.rb
class Tutor < ApplicationRecord
  belongs_to :familia
end

app/models/unidade.rb
class Unidade < ApplicationRecord
  belongs_to :laboratorio
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_gravatar
end

app/controllers/familias_controller.rb
class FamiliasController < OrganizacoesController

  before_action :authenticate_user!
  before_action :set_familia, only: [:edit, :add_tutor, :add_paciente]


  layout 'clinica'
  
  def edit
    @tutor = Tutor.new
    @paciente = Paciente.new
  end

  def new
    @familia = Familia.create(clinica: @clinica)

    # Adicionar em última familia?

    redirect_to edit_familia_path(@familia)
  end

  def add_tutor
    @tutor = Tutor.new(tutor_params)
    @tutor.familia = @familia
    @tutor.save

    redirect_to edit_familia_path(@familia)
  end

  def add_paciente
    @paciente = Paciente.new(paciente_params)
    @paciente.familia = @familia
    if params['paciente']['sexo'] == 'masculino'
      @paciente.sexo = true
    else
      @paciente.sexo = false
    end
      
    @paciente.save

    redirect_to edit_familia_path(@familia)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_familia
    @familia = Familia.where(id: params[:id], clinica: @clinica).take
  end

  def tutor_params
    params.require(:tutor).permit(:nome, :telefones, :email, :cpf)
  end

  def paciente_params
    params.require(:paciente).permit(:nome, :raca, :especie, :data_nacimento, :sexo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinicas_helper.rb
module ClinicasHelper
end

app/helpers/familias_helper.rb
module FamiliasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tutores_helper.rb
module TutoresHelper
end

app/views/familias/_pacientes_form.erb
<h2>Novo Paciente</h2>
<%= form_for [familia, paciente], url: add_paciente_familia_path(familia) do |f| %>

  <div class="form-row">
    <div class="form-group col-md-6">
    <%= f.label :nome, 'Nome' %><br />
    <%= f.text_field :nome, placeholder: 'Nome do paciente', class: 'form-control' %>
    </div>
    <div class="form-group col-md-auto">
      <%= f.label :sexo, 'Sexo' %><br />
      <%= f.radio_button(:sexo, 'feminino') %>
      <%= f.label :sexo_feminino, 'Feminino' %>
      <%= f.radio_button(:sexo, 'masculino') %>
      <%= f.label :sexo_masculino, 'Masculino' %>
    </div>
    <div class="form-group col-md-auto">
      <%= f.label(:data_nascimento) %><br />
      <%= f.date_field(:data_nascimento) %>
    </div>


  </div>

  <div class="form-row">
    <div class="form-group col-sm-5">
      <%= f.text_field :especie, id: :exame_requisicao_especie, placeholder: 'Espécie do paciente', class: 'form-control', list: 'especies' %>
      <datalist id="especies">
        <option value="Aves">
        <option value="Bovina">
        <option value="Canina">
        <option value="Caprina">
        <option value="Equina">
        <option value="Felina">
        <option value="Ouvina">
        <option value="Roedores">
        <option value="Outras">
      </datalist>
    </div>
    <div class="form-group col-sm-5">
      <%= f.text_field :raca, id: :exame_requisicao_raca, placeholder: 'Raça do paciente', class: 'form-control' %>
    </div>
    <div class="actions form-group col-sm-2">
      <%= f.submit 'Adicionar paciente', class: "btn btn-primary" %>      
    </div>
  </div>

  
<% end %>

app/views/familias/_tutores_form.erb
<h2>Novo Tutor</h2>
<%= form_for [familia, tutor], url: add_tutor_familia_path(familia) do |f| %>

  <div class="form-group">
    <%= f.text_field :nome, autofocus: true, placeholder: 'Nome do tutor', class: 'form-control' %>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.telephone_field :telefones, autocomplete: "telefone", placeholder: 'Telefone', class: 'form-control' %>
    </div>
    <div class="form-group col-md-6">
      <%= f.text_field :cpf, placeholder: 'CPF', class: 'form-control' %>
    </div>
  </div>
  
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.email_field :email, autocomplete: "email", placeholder: 'e-mail', class: 'form-control' %>
    </div>
    <div class="actions form-group col-md-6">
      <%= f.submit 'Adicionar tutor', class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/familias/edit.html.erb
<% provide(:title, 'Cadastro de pacientes e família') %>


<div class="container">

<h1>Cadastrando família (tutores e pacientes)</h1>


<div class="row">
  <div class="col-sm-6">
    <div class="card" id="tutores_cadastrados">
      <div class="card-body">
        <h5 class="card-title">Tutores</h5>
<!--% unless familia.tutores.empty? %-->
    <ul>
    <% @familia.tutores.each do |tutor| %>
      <li><%= tutor.nome %> (<%= tutor.telefones %>) </li>
    <% end %>
    </ul>
<!--% end %-->
      </div>
    </div>
  </div>
  <div class="col-sm-6" id="pacientes_cadastrados">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Pacientes</h5>
<!--% unless familia.tutores.empty? %-->

    <% @familia.pacientes.each do |p| %>
      <p>
        <%= p.nome %> 
        <div class="btn-group btn-group-sm" role="group">
          <%= link_to "Iniciar atendimento", new_paciente_atendimento_path(p), class: "btn btn-secondary", id: "new_paciente_atendimento_#{p.id}" %>
        </div>
      </p>
    <% end %>

<!--% end %-->
      </div>
    </div>
  </div>
</div>
<small id="AdiconarHelp" class="form-text text-muted">Você pode cadastrar vários tutores e pacientes que compõem a 'família'.</small>
<%= render 'tutores_form', familia: @familia, tutor: @tutor %>
<%= render 'pacientes_form', familia: @familia, paciente: @paciente %>



</div>